---
title: "Supplementary Information: *Relative model selection of evolutionary substitution models is sensitive to multiple sequence alignment uncertainty*"
author: "Stephanie J. Spielman* and Molly Miraglia"
date: "*Corresponding author: spielman@rowan.edu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo    = FALSE, 
                      include = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
library(gt)
gtify <- function(df, ic)
{
  df %>%
    gt::gt() %>%
    gt::cols_align(
      align = "left"
    ) %>%
    tab_header(
      title = "SP and TC scores comparisons among groups",
      subtitle = glue::glue("Model selection with ", ic)
    ) %>%
     tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_body(
        columns = c(Datatype, Comparison, `Score type`, `Effect size (99% CI)`, `Adjusted P-value`),
        rows = `Adjusted P-value` <= 0.05)
    )
}
```

<br><br><br>

# Additional Figures

<br>

### Figure S1

<br>

```{r, fig.width = 13, fig.height = 8}

plot_howmanymodels(howmanymodels_plot_data, "BIC") + 
  ggtitle("Model selection with BIC")-> bar_howmanymodels_bic 
plot_percentm0(percent_top_models, "BIC") + 
  ggtitle("Model selection with BIC")-> percentm0_bic

plot_howmanymodels(howmanymodels_plot_data, "AICc") +
  ggtitle("Model selection with AICc") -> bar_howmanymodels_aicc 
plot_percentm0(percent_top_models, "AICc") +
  ggtitle("Model selection with AICc") -> percentm0_aicc 


plot_grid(bar_howmanymodels_bic, 
          percentm0_bic,
          nrow=1, labels = "auto", scale = 0.95, label_size = 18) -> ab

plot_grid(bar_howmanymodels_aicc, 
          percentm0_aicc,
          nrow=1, labels = c("c", "d"), scale = 0.95, label_size = 20) -> cd

plot_grid(ab, cd, nrow = 2)
```

<br><br>

### Figure S2

<br>


```{r, fig.width = 6, fig.height = 3}
# Barplot of matrix stability for n_models >1 with AICc and BIC
full_join(how_many_models, how_many_matrices) %>%
  filter(n_models > 1, ic_type != "AIC") %>%
  mutate(qstability = ifelse(n_matrices == 1, "Same Q matrix", "Different Q matrices")) %>%
  # have to count for a geom_text
  count(dataset, datatype, qstability) %>%
  group_by(dataset, datatype) %>%
  mutate(total = sum(n)) %>%
  ungroup() %>%
  filter(qstability == "Same Q matrix") %>%
  mutate(p = round(n/total, 2)) %>%
  mutate(fudge = p+0.02) %>%
  ggplot(aes(x = datatype, y = p, fill = dataset)) + 
  geom_col(color = "black", size = 0.3, position = position_dodge()) + 
  geom_text(aes(label = p, y = fudge), size = 3, position = position_dodge(width = 1))+
  scale_fill_viridis_d(name = "", option = "magma") +
  xlab("Data Type") +
  ylab("Proportion of unstable datasets\nwith a stable Q matrix") + 
  theme(legend.position = "bottom",
        axis.title.y = element_text(size = rel(0.8)),
        panel.grid.minor.y = element_blank(),
        legend.key.size = unit(0.4, "cm")) 
```

<br><br>

### Figure S3

<br>

```{r, fig.width = 10, fig.height = 3.5}
plot_scores_boxplot(scores_plot_data, "BIC") + 
  ggtitle("Model selection with BIC")  -> scores_boxplot_bic
plot_scores_boxplot(scores_plot_data, "AICc") + 
  ggtitle("Model selection with AICc") + 
  theme(legend.position = "none") -> scores_boxplot_aicc

shared_legend <- get_legend(scores_boxplot_bic)

plot_grid(
  scores_boxplot_bic + theme(legend.position = "none") ,
  scores_boxplot_aicc,
  nrow = 1, 
  scale = 0.97,
  labels = "auto") -> part1

plot_grid(part1, shared_legend, nrow = 2, rel_heights = c(1, 0.3))
```

\newpage

# Additional Tables

<br>

### Table S1

```{r}
modeled_scores_table %>%
  filter(ic_type == "BIC") %>%
  select(-ic_type) %>%
  gtify("BIC")
```
<br>

\newpage

### Table S2
```{r}
modeled_scores_table %>%
  filter(ic_type == "AICc") %>%
  select(-ic_type) %>%
  gtify("AICc")
```